"""Lightweight, cache-aware backtesting utilities."""

from .chart_snapshot import ChartSnapshotArtifact, ChartSnapshotExporter
from .engine import BacktestConfig, BacktestEngine, BacktestResult
from .catalog import ResultCatalog
from .data_loader import load_csv_prices, resample_bars
from .duckdb_store import DuckDBStore
from .engine_comparison import (
    EngineBatchComparisonSummary,
    EngineComparisonSummary,
    EngineRunSnapshot,
    duration_seconds,
    summarize_engine_batch,
    summarize_engine_runs,
)
from .execution import (
    BatchExecutionBenchmark,
    ExecutionMode,
    ExecutionOrchestrator,
    ExecutionRequest,
    ExecutionResult,
    PortfolioExecutionAsset,
    PortfolioExecutionRequest,
    PortfolioExecutionResult,
    UnsupportedExecutionModeError,
    WorkloadType,
)
from .grid_search import (
    GridSearch,
    GridSpec,
    IndependentAssetStudyBenchmark,
    IndependentAssetTarget,
    PortfolioAssetTarget,
    build_horizons,
    run_independent_asset_grid_search,
    run_vectorized_portfolio_grid_search,
)
from .reference_engine import ReferenceEngine
from .portfolio_reporting import (
    PortfolioAssetAttribution,
    PortfolioChartData,
    PortfolioReport,
    build_portfolio_chart_data,
    portfolio_report_frame,
    summarize_portfolio_result,
)
from .reporting import plot_param_heatmap
from .vectorized_engine import VectorizedEngine
from .vectorized_portfolio import (
    ALLOCATION_OWNERSHIP_HYBRID,
    ALLOCATION_OWNERSHIP_PORTFOLIO,
    ALLOCATION_OWNERSHIP_STRATEGY,
    PortfolioAssetSpec,
    PortfolioConstructionConfig,
    PortfolioTrade,
    RANKING_MODE_NONE,
    RANKING_MODE_SCORE_THRESHOLD,
    RANKING_MODE_TOP_N,
    RANKING_MODE_TOP_N_OVER_SCORE_THRESHOLD,
    REBALANCE_MODE_ON_CHANGE,
    REBALANCE_MODE_ON_CHANGE_OR_DRIFT,
    REBALANCE_MODE_ON_CHANGE_OR_PERIODIC,
    REBALANCE_MODE_ON_CHANGE_OR_PERIODIC_OR_DRIFT,
    WEIGHTING_MODE_EQUAL_SELECTED,
    WEIGHTING_MODE_PRESERVE,
    WEIGHTING_MODE_SCORE_PROPORTIONAL,
    VectorizedPortfolioEngine,
    VectorizedPortfolioResult,
)
from .sample_strategies import InverseTurtleStrategy, SMACrossStrategy, ZScoreMeanReversionStrategy

__all__ = [
    "ChartSnapshotArtifact",
    "ChartSnapshotExporter",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "ALLOCATION_OWNERSHIP_HYBRID",
    "ALLOCATION_OWNERSHIP_PORTFOLIO",
    "ALLOCATION_OWNERSHIP_STRATEGY",
    "ResultCatalog",
    "DuckDBStore",
    "EngineBatchComparisonSummary",
    "EngineComparisonSummary",
    "EngineRunSnapshot",
    "BatchExecutionBenchmark",
    "ExecutionMode",
    "ExecutionOrchestrator",
    "ExecutionRequest",
    "ExecutionResult",
    "PortfolioExecutionAsset",
    "PortfolioExecutionRequest",
    "PortfolioExecutionResult",
    "GridSearch",
    "GridSpec",
    "IndependentAssetStudyBenchmark",
    "IndependentAssetTarget",
    "PortfolioAssetTarget",
    "ReferenceEngine",
    "UnsupportedExecutionModeError",
    "VectorizedEngine",
    "VectorizedPortfolioEngine",
    "VectorizedPortfolioResult",
    "PortfolioAssetSpec",
    "PortfolioConstructionConfig",
    "PortfolioTrade",
    "PortfolioAssetAttribution",
    "PortfolioChartData",
    "PortfolioReport",
    "RANKING_MODE_NONE",
    "RANKING_MODE_SCORE_THRESHOLD",
    "RANKING_MODE_TOP_N",
    "RANKING_MODE_TOP_N_OVER_SCORE_THRESHOLD",
    "REBALANCE_MODE_ON_CHANGE",
    "REBALANCE_MODE_ON_CHANGE_OR_DRIFT",
    "REBALANCE_MODE_ON_CHANGE_OR_PERIODIC",
    "REBALANCE_MODE_ON_CHANGE_OR_PERIODIC_OR_DRIFT",
    "WEIGHTING_MODE_EQUAL_SELECTED",
    "WEIGHTING_MODE_PRESERVE",
    "WEIGHTING_MODE_SCORE_PROPORTIONAL",
    "WorkloadType",
    "build_horizons",
    "duration_seconds",
    "load_csv_prices",
    "resample_bars",
    "run_independent_asset_grid_search",
    "run_vectorized_portfolio_grid_search",
    "summarize_engine_batch",
    "summarize_engine_runs",
    "SMACrossStrategy",
    "InverseTurtleStrategy",
    "ZScoreMeanReversionStrategy",
    "plot_param_heatmap",
    "build_portfolio_chart_data",
    "portfolio_report_frame",
    "summarize_portfolio_result",
]
